// Generated by https://quicktype.io

export interface SearchApi {
  Search:       Movie[];
  totalResults: string;
  Response:     string;
}

export interface Movie {
  Title:  string;
  Year:   string;
  imdbID: string;
  Type:   string;
  Poster: string;
}

export enum Type {
  Movie = "movie",
  Series = "series",
}
